### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Connor-Knabe** [nicjansma/spark-core-water-sensor#1]
Have you ever had a false positive with this setup?  I have mine setup near a pool pump and twice it has gone off (falsely) about 10 minutes after the pool pump flips on.  They both are using the same outlet. Maybe the pump is drawing too much power which takes some away from the Photon? 

Also have you attempted to hook multiple water sensors into the photon like wiring 3 of them to the same pins?

**Comment by nicjansma** [comment]
Hi Connor,

I haven't had any false positives so far, but I'm also using it indoors.  Is it possible that outdoor humidity around the pool is shorting the sensor somehow?  Are you using the Grove Water Sensor like I am?  It's also quite possible the power draw is affecting it.  Maybe put it on a different outlet, or temporarily on battery power to diagnose if that's the issue?

I don't think having all sensors all on the same digital pin would work, but you could easily power all of the sensors with 3.3v and Ground, and have each sensors's output on one of the remaining 6 digital pins.  The `isExposedToWater` function could be pretty easily updated to read all 6 pins.

**Comment by Connor-Knabe** [comment]
Yep I'm using the Grove Water Sensor also.  I'll attempt it on a new outlet and see if it fixes things. Thanks!

**Comment by Connor-Knabe** [comment]
This seemed to fix the issue. :+1:
